version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_thi_sinh

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: quanlythisinh
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d

volumes:
  mysql_data:
